name: "E2E Test Coverage"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight

env:
  NODE_DEFAULT_VERSION: 20
  NODE_OPTIONS: "--max_old_space_size=4096"
  HEADLESS: true
  WORKERS: 1
  RETRIES: 2
  TIMEOUT: 180000
  ENV: local

jobs:
  e2e-coverage:
    name: E2E Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v4

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_DEFAULT_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            e2e-tests/package-lock.json

      - name: "Install root dependencies"
        run: |
          echo "Installing root dependencies..."
          npm ci --ignore-scripts --no-audit --prefer-offline || npm ci --ignore-scripts --no-audit

      - name: "Install e2e-tests dependencies"
        run: |
          cd e2e-tests
          echo "Installing e2e-tests dependencies..."
          npm ci --no-audit --prefer-offline || npm ci --no-audit

      - name: "Install Playwright browsers"
        run: |
          cd e2e-tests
          echo "Installing Playwright browsers..."
          npx playwright install --with-deps chromium

      - name: "Start Juice Shop application"
        run: |
          echo "Starting Juice Shop application..."
          npm start &
          echo "Waiting for application to start..."
          # Wait for the application to start (up to 120 seconds)
          timeout=120
          while [ $timeout -gt 0 ]; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is running at http://localhost:3000"
              break
            fi
            echo "Waiting for Juice Shop to start... ($timeout seconds left)"
            sleep 10
            timeout=$((timeout - 10))
          done
          
          if [ $timeout -le 0 ]; then
            echo "Timed out waiting for Juice Shop to start"
            exit 1
          fi
          
          # Additional wait to ensure the app is fully initialized
          sleep 30
          echo "Juice Shop is ready for testing"

      - name: "Run Playwright tests with coverage"
        run: |
          cd e2e-tests
          mkdir -p playwright-report test-results coverage-report
          echo "Running Playwright tests..."
          CI=true ENV=local BASE_URL=http://localhost:3000 npx playwright test --config=config/env.config.ts --reporter=json,html --timeout=180000 --retries=3 --workers=1 || echo "Tests completed with some failures"

      - name: "Generate coverage report"
        run: |
          cd e2e-tests
          npm run coverage

      - name: "Upload coverage report"
        uses: actions/upload-artifact@v4
        with:
          name: e2e-coverage-report
          path: |
            e2e-tests/coverage-report
          retention-days: 30
